# linear offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_train --num_train_epochs 2 --save_strategy steps  --train_file ../unilm/simlm/data/msmarco_bm25_official/train.jsonl --validation_file ../unilm/simlm/data/msmarco_bm25_official/dev.jsonl --output_dir simlm-base-msmarco-finetuned_ls32 --data_dir  ../unilm/simlm/data/msmarco_bm25_official/ --fp16 --per_device_train_batch_size 128 --train_n_passages 32 --model_type linear_offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_eval  --validation_file ../unilm/simlm/simlm-base-msmarco-finetuned/dev.msmarco.jsonl --output_dir simlm-base-msmarco-finetuned_ls32  --data_dir  ../unilm/simlm/data/msmarco_bm25_official/   --train_n_passages 1000 --model_type linear_offset

# sqrt offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_train --num_train_epochs 2 --save_strategy steps  --train_file ../unilm/simlm/data/msmarco_bm25_official/train.jsonl --validation_file ../unilm/simlm/data/msmarco_bm25_official/dev.jsonl --output_dir simlm-base-msmarco-finetuned_ls32_sqrt --data_dir  ../unilm/simlm/data/msmarco_bm25_official/ --fp16 --per_device_train_batch_size 128 --train_n_passages 32 --model_type sqrt_offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_eval  --validation_file ../unilm/simlm/simlm-base-msmarco-finetuned/dev.msmarco.jsonl --output_dir simlm-base-msmarco-finetuned_ls32_sqrt  --data_dir  ../unilm/simlm/data/msmarco_bm25_official/   --train_n_passages 1000 --model_type sqrt_offset

# quadratic offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_train --num_train_epochs 2 --save_strategy steps  --train_file ../unilm/simlm/data/msmarco_bm25_official/train.jsonl --validation_file ../unilm/simlm/data/msmarco_bm25_official/dev.jsonl --output_dir simlm-base-msmarco-finetuned_ls32_quadratic --data_dir  ../unilm/simlm/data/msmarco_bm25_official/ --fp16 --per_device_train_batch_size 128 --train_n_passages 32 --model_type quadratic_offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_eval  --validation_file ../unilm/simlm/simlm-base-msmarco-finetuned/dev.msmarco.jsonl --output_dir simlm-base-msmarco-finetuned_ls32_quadratic  --data_dir  ../unilm/simlm/data/msmarco_bm25_official/   --train_n_passages 1000 --model_type quadratic_offset

# power offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_train --num_train_epochs 2 --save_strategy steps  --train_file ../unilm/simlm/data/msmarco_bm25_official/train.jsonl --validation_file ../unilm/simlm/data/msmarco_bm25_official/dev.jsonl --output_dir simlm-base-msmarco-finetuned_ls32_power --data_dir  ../unilm/simlm/data/msmarco_bm25_official/ --fp16 --per_device_train_batch_size 128 --train_n_passages 32 --model_type polynomial_offset
python train.py --model_name_or_path intfloat/simlm-base-msmarco-finetuned --do_eval  --validation_file ../unilm/simlm/simlm-base-msmarco-finetuned/dev.msmarco.jsonl --output_dir simlm-base-msmarco-finetuned_ls32_power  --data_dir  ../unilm/simlm/data/msmarco_bm25_official/   --train_n_passages 1000 --model_type polynomial_offset
